recipe: default.v1
language: fr
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
    epochs: 2
    random_seed: 2
    constrain_similarities: True
policies:
  - name : FormPolicy
  - name : RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    constrain_similarities: true

# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize tem, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     constrain_similarities: true
