version: "3.0"
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
    BILOU_flag: True
    features: [ [low, title, upper],
    [bias, low, prefix5, prefix2, suffix5, suffix3, suffix2, upper, title, digit, pattern], 
    [low, title, upper] ]
    max_iterations: 100
    L1_c: 0.1
    L2_c: 0.2
    featurizers: []
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1
  - name: EntitySynonymMapper
    epochs: 200
    random_seed: 2
  - name: ResponseSelector
    epochs: 300
    constrain_similarities: True
  ##- name: "DucklingEntityExtractor"
    ##url: "http://localhost:8000"
    ##dimensions: ["amount-of-money"]
    ##timeout : 5

policies:
  - name: AugmentedMemoizationPolicy
    max_history: 5
    epochs: 200
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    batch_size:
      - 32
      - 64
  - name: RulePolicy
    max_history: 5
    epochs: 200
    batch_size:
      - 32
      - 64
